# Pull the latest production Docker image from Docker Hub on schedule
name: Pull Docker Images

on:
  schedule:
    # Runs "At 00:00 on day-of-month 1 in every 2nd month."
    - cron: '0 0 1 */2 *'

jobs:
  pull-images:
    name: Pull Development Image
    runs-on: ubuntu-latest
    steps:
      - name: Pull Production Image
        run: docker compose -f docker-compose.prod.yml pull
