# Pull the latest production Docker image from Docker Hub on schedule
name: Pull Docker Images

on:
  schedule:
    # Runs "At 00:00 on day-of-month 1 in every month."
    - cron: '0 0 1 */1 *'
  push:
    branches-ignore:
      - 'main'

jobs:
  pull-images:
    name: Pull Development Image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3

      - name: Pull Production Image
        run: docker compose -f docker-compose.prod.yml pull
