# This workflow publishes a NodeJS package to npm when a release is created
# It also deploys the "latest" and tag development Docker image to Docker Hub

name: Publish to Docker Hub

on:
  release:
    types: [published]

jobs:
  run-tests:
    name: Run Tests
    if: github.event.release.target_commitish == 'main'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.release.tag_name }}

      - name: Use NodeJS v20.15.0
        uses: actions/setup-node@v3
        with:
          node-version: 20.15.0
          registry-url: https://registry.npmjs.org/

      - name: Install Dependencies
        run: npm install

      - name: Lint
        run: npm run lint

      - name: Transpile
        run: npm run transpile

  docker-build-push:
    name: Push Production Image
    if: github.event.release.target_commitish == 'main' && vars.DOCKERHUB_USERNAME != ''
    runs-on: ubuntu-latest
    needs: run-tests
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Checkout the repository
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.release.tag_name }}

      - name: Build Image
        run: docker compose -f docker-compose.prod.yml build

      - name: Push Image to Docker Hub
        run: docker compose -f docker-compose.prod.yml push
